Repository debate-timer/debate-timer-be, pull requests merged in 2024-12, with the labels that each got.

#11 [DOCS] 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/chore-template.md
  .github/ISSUE_TEMPLATE/docs-template.md
  .github/ISSUE_TEMPLATE/feat-template.md
  .github/ISSUE_TEMPLATE/fix-template.md
  .github/ISSUE_TEMPLATE/hotfix-template.md
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/ISSUE_TEMPLATE/refactor-template.md
  .github/ISSUE_TEMPLATE/test-template.md
  .github/workflows/Auto_Issue_Setting.yml
Labels: docs

#9 [FEAT] 초기 프로젝트 세팅
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/debatetimer/DebateTimerApplication.java
  src/main/java/com/debatetimer/controller/.gitkeep
  src/main/java/com/debatetimer/domain/.gitkeep
  src/main/java/com/debatetimer/repository/.gitkeep
  src/main/java/com/debatetimer/service/.gitkeep
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/com/debatetimer/DebateTimerApplicationTest.java
Labels: feat

#18 [FIX] 이슈 템플릿 작성 시, Assignees 자동 할당
  .github/workflows/Auto_Issue_Setting.yml
Labels: fix

#15 [CHORE] Swagger 문서화 환경 세팅
  build.gradle
  src/main/java/com/debatetimer/swagger/annotation/ErrorCode400.java
  src/main/java/com/debatetimer/swagger/annotation/ErrorCode401.java
  src/main/java/com/debatetimer/swagger/annotation/ErrorCode404.java
  src/main/java/com/debatetimer/swagger/annotation/ErrorCode500.java
  src/main/java/com/debatetimer/swagger/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: chore

#26 [REFACTOR] 알림 워크플로우 타이틀 수정
  .github/workflows/PR_Comment_Notification.yml
Labels: refactor

#21 [CHORE] CI 스크립트 작성
  .github/workflows/Dev_CI.yml
  build.gradle
  src/lombok.config
Labels: chore

#29 [CHORE] /noti 기능에 멘션 추가
  .github/workflows/PR_Comment_Notification.yml
Labels: chore

#30 [TEST] BaseXXXTest 환경 세팅하기
  src/test/java/com/debatetimer/BaseControllerTest.java
  src/test/java/com/debatetimer/BaseRepositoryTest.java
  src/test/java/com/debatetimer/BaseServiceTest.java
  src/test/java/com/debatetimer/DataBaseCleaner.java
Labels: test

#32 [FEAT] Entity 및 DB 세팅
  src/main/java/com/debatetimer/domain/.gitkeep
  src/main/java/com/debatetimer/domain/BoxType.java
  src/main/java/com/debatetimer/domain/Member.java
  src/main/java/com/debatetimer/domain/Stance.java
  src/main/java/com/debatetimer/domain/parliamentary_debate/ParliamentaryTable.java
  src/main/java/com/debatetimer/domain/parliamentary_debate/ParliamentaryTimeBox.java
  src/main/resources/application-local.yml
  src/test/java/com/debatetimer/domain/MemberTest.java
  src/test/java/com/debatetimer/domain/parliamentary_debate/ParliamentaryTableTest.java
  src/test/java/com/debatetimer/domain/parliamentary_debate/ParliamentaryTimeBoxTest.java
Labels: feat

#37 [FIX] 디스코드 알림 기능 수정
  .github/workflows/PR_Comment_Notification.yml
Labels: fix
