Repository debate-timer/debate-timer-be, pull requests merged in 2025-04, with the labels that each got.

#137 [FEAT] 발언자 길이 및 발언유형 길이 검증
  src/main/java/com/debatetimer/domain/DebateTimeBox.java
  src/main/java/com/debatetimer/domain/customize/CustomizeTimeBox.java
  src/main/java/com/debatetimer/exception/errorcode/ClientErrorCode.java
  src/test/java/com/debatetimer/domain/DebateTimeBoxTest.java
  src/test/java/com/debatetimer/domain/customize/CustomizeTimeBoxTest.java
Labels: feat

#141 [REFACTOR] Blank 검증을 DTO에서 일관성있게 수행
  src/main/java/com/debatetimer/domain/DebateTable.java
  src/main/java/com/debatetimer/domain/DebateTimeBox.java
  src/main/java/com/debatetimer/domain/customize/CustomizeTable.java
  src/main/java/com/debatetimer/domain/customize/CustomizeTimeBox.java
  src/main/java/com/debatetimer/dto/customize/request/CustomizeTableCreateRequest.java
  src/main/java/com/debatetimer/dto/customize/request/CustomizeTimeBoxCreateRequest.java
  src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableCreateRequest.java
  src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTimeBoxCreateRequest.java
  src/main/java/com/debatetimer/dto/timebased/request/TimeBasedTableCreateRequest.java
  src/main/java/com/debatetimer/dto/timebased/request/TimeBasedTimeBoxCreateRequest.java
  src/test/java/com/debatetimer/domain/DebateTableTest.java
  src/test/java/com/debatetimer/domain/DebateTimeBoxTest.java
  src/test/java/com/debatetimer/domain/customize/CustomizeTableTest.java
  src/test/java/com/debatetimer/domain/customize/CustomizeTimeBoxTest.java
Labels: refactor

#146 [FEAT] 자유 토론 타임 박스 nullable 수정
  src/main/java/com/debatetimer/domain/customize/CustomizeTimeBox.java
  src/main/java/com/debatetimer/domain/timebased/TimeBasedTimeBox.java
  src/main/java/com/debatetimer/dto/customize/request/CustomizeTimeBoxCreateRequest.java
  src/main/java/com/debatetimer/dto/timebased/request/TimeBasedTimeBoxCreateRequest.java
  src/main/java/com/debatetimer/exception/errorcode/ClientErrorCode.java
  src/test/java/com/debatetimer/domain/customize/CustomizeTimeBoxTest.java
  src/test/java/com/debatetimer/domain/timebased/TimeBasedTimeBoxTest.java
Labels: feat

#143 [REFACTOR] 회원 테이블 조회 시 커스텀 테이블 포함
  src/main/java/com/debatetimer/dto/member/TableResponses.java
  src/main/java/com/debatetimer/service/member/MemberService.java
  src/test/java/com/debatetimer/controller/member/MemberControllerTest.java
  src/test/java/com/debatetimer/service/member/MemberServiceTest.java
Labels: refactor

#145 [REFACTOR] speakerNumber parseInt에 따른 NPE 문제 개선
  src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBox.java
  src/main/java/com/debatetimer/dto/parliamentary/response/ParliamentaryTimeBoxResponse.java
  src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBoxTest.java
Labels: refactor

#148 [REFACTOR] time_based 일 때 time을 null로 반환
  src/main/java/com/debatetimer/dto/customize/response/CustomizeTimeBoxResponse.java
Labels: refactor

#149 [CHORE] 모니터링 설정 추가
  build.gradle
  scripts/dev/replace-new-version.sh
  scripts/prod/replace-new-version.sh
  src/main/resources/application-monitor.yml
  src/test/java/com/debatetimer/domain/TimeBoxesTest.java
Labels: chore

#154 [FEAT] AsyncRequestNotUsableException 에러 처리
  src/main/java/com/debatetimer/exception/handler/GlobalExceptionHandler.java
Labels: feat
