Repository debate-timer/debate-timer-be, pull requests merged in 2025-02, with the labels that each got.

#61 [FEAT] 구글 OAuth 도입
  build.gradle
  src/main/java/com/debatetimer/client/OAuthClient.java
  src/main/java/com/debatetimer/client/OAuthProperties.java
  src/main/java/com/debatetimer/config/AuthMemberArgumentResolver.java
  src/main/java/com/debatetimer/config/AuthenticationConfig.java
  src/main/java/com/debatetimer/config/WebConfig.java
  src/main/java/com/debatetimer/controller/member/MemberController.java
  src/main/java/com/debatetimer/controller/tool/cookie/CookieExtractor.java
  src/main/java/com/debatetimer/controller/tool/cookie/CookieManager.java
  src/main/java/com/debatetimer/controller/tool/cookie/CookieProvider.java
  src/main/java/com/debatetimer/controller/tool/jwt/AuthManager.java
  src/main/java/com/debatetimer/controller/tool/jwt/JwtTokenProperties.java
  src/main/java/com/debatetimer/controller/tool/jwt/JwtTokenProvider.java
  src/main/java/com/debatetimer/controller/tool/jwt/JwtTokenResolver.java
  src/main/java/com/debatetimer/controller/tool/jwt/TokenType.java
  src/main/java/com/debatetimer/domain/member/Member.java
  src/main/java/com/debatetimer/dto/member/JwtTokenResponse.java
  src/main/java/com/debatetimer/dto/member/MemberCreateRequest.java
  src/main/java/com/debatetimer/dto/member/MemberCreateResponse.java
  src/main/java/com/debatetimer/dto/member/MemberInfo.java
  src/main/java/com/debatetimer/dto/member/OAuthToken.java
  src/main/java/com/debatetimer/exception/errorcode/ClientErrorCode.java
  src/main/java/com/debatetimer/repository/member/MemberRepository.java
  src/main/java/com/debatetimer/service/auth/AuthService.java
  src/main/java/com/debatetimer/service/member/MemberService.java
  src/main/resources/application-dev.yml
  src/test/java/com/debatetimer/controller/BaseControllerTest.java
  src/test/java/com/debatetimer/controller/BaseDocumentTest.java
  src/test/java/com/debatetimer/controller/RestDocumentationRequest.java
  src/test/java/com/debatetimer/controller/RestDocumentationResponse.java
  src/test/java/com/debatetimer/controller/member/MemberControllerTest.java
  src/test/java/com/debatetimer/controller/member/MemberDocumentTest.java
  src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerTest.java
  src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryDocumentTest.java
  src/test/java/com/debatetimer/controller/tool/cookie/CookieExtractorTest.java
  src/test/java/com/debatetimer/controller/tool/jwt/JwtTokenResolverTest.java
  src/test/java/com/debatetimer/domain/member/MemberTest.java
  src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTableTest.java
  src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBoxesTest.java
  src/test/java/com/debatetimer/fixture/CookieGenerator.java
  src/test/java/com/debatetimer/fixture/HeaderGenerator.java
  src/test/java/com/debatetimer/fixture/JwtTokenFixture.java
  src/test/java/com/debatetimer/fixture/MemberGenerator.java
  src/test/java/com/debatetimer/fixture/TokenGenerator.java
  src/test/java/com/debatetimer/repository/member/MemberRepositoryTest.java
  src/test/java/com/debatetimer/repository/parliamentary/ParliamentaryTableRepositoryTest.java
  src/test/java/com/debatetimer/repository/parliamentary/ParliamentaryTimeBoxRepositoryTest.java
  src/test/java/com/debatetimer/service/BaseServiceTest.java
  src/test/java/com/debatetimer/service/auth/AuthServiceTest.java
  src/test/java/com/debatetimer/service/member/MemberServiceTest.java
  src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
  src/test/resources/application.yml
Labels: feat

#84 [FIX] yml파일 수정
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: fix

#86 chore: db 방언 직접 지정
  src/main/resources/application-dev.yml
Labels: fix

#89 [FIX] redirect_url_mismatch 문제 해결
  .gitignore
  src/main/java/com/debatetimer/client/OAuthProperties.java
  src/main/java/com/debatetimer/dto/member/MemberCreateRequest.java
  src/test/java/com/debatetimer/controller/member/MemberControllerTest.java
  src/test/java/com/debatetimer/controller/member/MemberDocumentTest.java
Labels: fix

#91 [FIX] 클라이언트에 헤더 및 쿠키 공개 설정 fix 기능 수정
  src/main/java/com/debatetimer/config/CorsConfig.java
  src/main/java/com/debatetimer/controller/member/MemberController.java
  src/main/java/com/debatetimer/controller/tool/cookie/CookieManager.java
  src/main/java/com/debatetimer/controller/tool/cookie/CookieProvider.java
  src/test/java/com/debatetimer/controller/BaseDocumentTest.java
  src/test/java/com/debatetimer/controller/GlobalControllerTest.java
  src/test/java/com/debatetimer/controller/member/MemberDocumentTest.java
  src/test/java/com/debatetimer/fixture/CookieGenerator.java
Labels: fix

#87 [DOCS] Swagger host 변경
  build.gradle
Labels: docs

#93 [REFACTOR] OAuth 및 Cookie 관련 코드 리팩토링 refactor 리팩토링
  src/main/java/com/debatetimer/controller/member/MemberController.java
  src/main/java/com/debatetimer/controller/tool/cookie/CookieExtractor.java
  src/main/java/com/debatetimer/controller/tool/cookie/CookieManager.java
  src/main/java/com/debatetimer/controller/tool/cookie/CookieProvider.java
  src/main/java/com/debatetimer/controller/tool/jwt/AuthManager.java
  src/main/java/com/debatetimer/controller/tool/jwt/JwtTokenProperties.java
  src/main/java/com/debatetimer/controller/tool/jwt/JwtTokenProvider.java
  src/main/java/com/debatetimer/dto/member/JwtTokenResponse.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/debatetimer/controller/BaseControllerTest.java
  src/test/java/com/debatetimer/controller/BaseDocumentTest.java
  src/test/java/com/debatetimer/controller/member/MemberDocumentTest.java
  src/test/java/com/debatetimer/controller/tool/cookie/CookieExtractorTest.java
  src/test/java/com/debatetimer/controller/tool/cookie/CookieProviderTest.java
  src/test/java/com/debatetimer/controller/tool/jwt/JwtTokenPropertiesTest.java
  src/test/java/com/debatetimer/fixture/CookieGenerator.java
  src/test/java/com/debatetimer/fixture/JwtTokenFixture.java
  src/test/java/com/debatetimer/service/BaseServiceTest.java
  src/test/resources/application.yml
Labels: refactor

#98 [FEAT] 단건 조회에 토론 형식을 같이 반환하도록 수정
  src/main/java/com/debatetimer/dto/parliamentary/response/TableInfoResponse.java
  src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryDocumentTest.java
Labels: feat

#99 [FEAT] 의회식 토론 EXPORT Api 구현
  src/main/java/com/debatetimer/config/CorsConfig.java
  src/main/java/com/debatetimer/config/WebConfig.java
  src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryController.java
  src/main/java/com/debatetimer/controller/tool/export/ExcelExport.java
  src/main/java/com/debatetimer/controller/tool/export/ExcelExportInterceptor.java
  src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
  src/main/java/com/debatetimer/view/exporter/ParliamentaryTableExcelExporter.java
  src/main/java/com/debatetimer/view/exporter/ParliamentaryTableExportMessageResolver.java
Labels: feat

#103 [REFACTOR] 스프링 시작 시 발생하는 예외 설정
  src/main/java/com/debatetimer/client/OAuthProperties.java
  src/main/java/com/debatetimer/config/CorsConfig.java
  src/main/java/com/debatetimer/controller/tool/jwt/JwtTokenProperties.java
  src/main/java/com/debatetimer/exception/custom/DTClientErrorException.java
  src/main/java/com/debatetimer/exception/custom/DTErrorResponseException.java
  src/main/java/com/debatetimer/exception/custom/DTInitializationException.java
  src/main/java/com/debatetimer/exception/custom/DTServerErrorException.java
  src/main/java/com/debatetimer/exception/errorcode/ClientErrorCode.java
  src/main/java/com/debatetimer/exception/errorcode/InitializationErrorCode.java
  src/main/java/com/debatetimer/exception/errorcode/ResponseErrorCode.java
  src/main/java/com/debatetimer/exception/errorcode/ServerErrorCode.java
  src/main/java/com/debatetimer/exception/handler/GlobalExceptionHandler.java
  src/test/java/com/debatetimer/client/OAuthPropertiesTest.java
  src/test/java/com/debatetimer/config/CorsConfigTest.java
  src/test/java/com/debatetimer/controller/tool/jwt/JwtTokenPropertiesTest.java
  src/test/resources/application.yml
Labels: refactor
