Repository debate-timer/debate-timer-be, pull requests merged in 2025-03, with the labels that each got.

#107 [CHORE] DB 형상 관리 도구 도입
  build.gradle
  src/main/java/com/debatetimer/DebateTimerApplication.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/db/migration/V1__initialize_table.sql
  src/main/resources/db/migration/V2__add_time_based_table.sql
  src/test/java/com/debatetimer/DatabaseSchemaManagerTest.java
  src/test/java/com/debatetimer/DebateTimerApplicationTest.java
  src/test/resources/application-flyway.yml
  src/test/resources/application.yml
Labels: chore

#110 [FEAT] 멤버의 테이블 조회 시, 테이블 순서 구현
  src/main/java/com/debatetimer/config/JpaAuditingConfig.java
  src/main/java/com/debatetimer/domain/BaseTimeEntity.java
  src/main/java/com/debatetimer/domain/DebateTable.java
  src/main/java/com/debatetimer/domain/member/Member.java
  src/main/java/com/debatetimer/dto/member/TableResponses.java
  src/main/resources/db/migration/V3__add_auditing_column.sql
  src/test/java/com/debatetimer/DatabaseSchemaManagerTest.java
  src/test/java/com/debatetimer/domain/DebateTableTest.java
  src/test/java/com/debatetimer/service/member/MemberServiceTest.java
Labels: feat

#113 [FIX] time auditing이 되지 않는 문제 개선
  src/main/java/com/debatetimer/domain/BaseTimeEntity.java
Labels: fix

#114 [REFACTOR] 멤버 테이블 조회에서 소요시간 대신 주제 반환
  src/main/java/com/debatetimer/domain/DebateTable.java
  src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTable.java
  src/main/java/com/debatetimer/domain/timebased/TimeBasedTable.java
  src/main/java/com/debatetimer/dto/member/TableResponse.java
  src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableCreateRequest.java
  src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableInfoCreateRequest.java
  src/main/java/com/debatetimer/dto/timebased/request/TimeBasedTableCreateRequest.java
  src/main/java/com/debatetimer/dto/timebased/request/TimeBasedTableInfoCreateRequest.java
  src/main/resources/db/migration/V4__drop_duration_column.sql
  src/test/java/com/debatetimer/controller/member/MemberControllerTest.java
  src/test/java/com/debatetimer/controller/member/MemberDocumentTest.java
  src/test/java/com/debatetimer/domain/DebateTableTest.java
  src/test/java/com/debatetimer/domain/TimeBoxesTest.java
  src/test/java/com/debatetimer/fixture/ParliamentaryTableGenerator.java
  src/test/java/com/debatetimer/fixture/TimeBasedTableGenerator.java
Labels: refactor

#118 [FEAT] 사용자 지정 테이블 Entity 구현
  src/main/java/com/debatetimer/domain/DebateTimeBox.java
  src/main/java/com/debatetimer/domain/customize/CustomizeBoxType.java
  src/main/java/com/debatetimer/domain/customize/CustomizeTable.java
  src/main/java/com/debatetimer/domain/customize/CustomizeTimeBox.java
  src/main/java/com/debatetimer/dto/member/TableType.java
  src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableCreateRequest.java
  src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableInfoCreateRequest.java
  src/main/resources/db/migration/V5__add_customize_table.sql
  src/test/java/com/debatetimer/domain/customize/CustomizeTableTest.java
  src/test/java/com/debatetimer/domain/customize/CustomizeTimeBoxTest.java
Labels: feat

#119 [FEAT] Debate API 구현
  src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryController.java
  src/main/java/com/debatetimer/controller/timebased/TimeBasedController.java
  src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableCreateRequest.java
  src/main/java/com/debatetimer/dto/timebased/request/TimeBasedTableCreateRequest.java
  src/main/java/com/debatetimer/repository/parliamentary/ParliamentaryTimeBoxRepository.java
  src/main/java/com/debatetimer/repository/timebased/TimeBasedTimeBoxRepository.java
  src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
  src/main/java/com/debatetimer/service/timebased/TimeBasedService.java
  src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerTest.java
  src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryDocumentTest.java
  src/test/java/com/debatetimer/controller/timebased/TimeBasedControllerTest.java
  src/test/java/com/debatetimer/controller/timebased/TimeBasedDocumentTest.java
  src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
  src/test/java/com/debatetimer/service/timebased/TimeBasedServiceTest.java
Labels: feat

#124 [FEAT] 사용자 지정 테이블 CRUD 구현
  src/main/java/com/debatetimer/controller/customize/CustomizeController.java
  src/main/java/com/debatetimer/domain/DebateTimeBox.java
  src/main/java/com/debatetimer/domain/customize/CustomizeTable.java
  src/main/java/com/debatetimer/domain/customize/CustomizeTimeBox.java
  src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBox.java
  src/main/java/com/debatetimer/domain/timebased/TimeBasedTimeBox.java
  src/main/java/com/debatetimer/dto/customize/request/CustomizeTableCreateRequest.java
  src/main/java/com/debatetimer/dto/customize/request/CustomizeTableInfoCreateRequest.java
  src/main/java/com/debatetimer/dto/customize/request/CustomizeTimeBoxCreateRequest.java
  src/main/java/com/debatetimer/dto/customize/response/CustomizeTableInfoResponse.java
  src/main/java/com/debatetimer/dto/customize/response/CustomizeTableResponse.java
  src/main/java/com/debatetimer/dto/customize/response/CustomizeTimeBoxResponse.java
  src/main/java/com/debatetimer/dto/parliamentary/response/ParliamentaryTimeBoxResponse.java
  src/main/java/com/debatetimer/dto/timebased/response/TimeBasedTimeBoxResponse.java
  src/main/java/com/debatetimer/repository/customize/CustomizeTableRepository.java
  src/main/java/com/debatetimer/repository/customize/CustomizeTimeBoxRepository.java
  src/main/java/com/debatetimer/repository/timebased/TimeBasedTimeBoxRepository.java
  src/main/java/com/debatetimer/service/customize/CustomizeService.java
  src/main/resources/db/migration/V7__speaker_modify_varchar.sql
  src/test/java/com/debatetimer/controller/BaseControllerTest.java
  src/test/java/com/debatetimer/controller/BaseDocumentTest.java
  src/test/java/com/debatetimer/controller/Tag.java
  src/test/java/com/debatetimer/controller/customize/CustomizeControllerTest.java
  src/test/java/com/debatetimer/controller/customize/CustomizeDocumentTest.java
  src/test/java/com/debatetimer/domain/DebateTimeBoxTest.java
  src/test/java/com/debatetimer/domain/customize/CustomizeTimeBoxTest.java
  src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBoxTest.java
  src/test/java/com/debatetimer/domain/timebased/TimeBasedTimeBoxTest.java
  src/test/java/com/debatetimer/fixture/CustomizeTableGenerator.java
  src/test/java/com/debatetimer/fixture/CustomizeTimeBoxGenerator.java
  src/test/java/com/debatetimer/repository/BaseRepositoryTest.java
  src/test/java/com/debatetimer/repository/customize/CustomizeTableRepositoryTest.java
  src/test/java/com/debatetimer/repository/customize/CustomizeTimeBoxRepositoryTest.java
  src/test/java/com/debatetimer/service/BaseServiceTest.java
  src/test/java/com/debatetimer/service/customize/CustomizeServiceTest.java
Labels: feat

#129 [REFACTOR] 테이블 명, 팀 이름 검증 수정
  src/main/java/com/debatetimer/domain/DebateTable.java
  src/main/java/com/debatetimer/domain/customize/CustomizeTable.java
  src/main/java/com/debatetimer/exception/errorcode/ClientErrorCode.java
  src/test/java/com/debatetimer/domain/DebateTableTest.java
  src/test/java/com/debatetimer/domain/customize/CustomizeTableTest.java
Labels: refactor

#126 [FEAT] 디스코드 알림 로직 추가
  build.gradle
  src/main/java/com/debatetimer/client/notifier/ConsoleNotifier.java
  src/main/java/com/debatetimer/client/notifier/DiscordNotifier.java
  src/main/java/com/debatetimer/client/notifier/DiscordProperties.java
  src/main/java/com/debatetimer/client/notifier/ErrorNotifier.java
  src/main/java/com/debatetimer/client/oauth/OAuthClient.java
  src/main/java/com/debatetimer/client/oauth/OAuthProperties.java
  src/main/java/com/debatetimer/config/AuthenticationConfig.java
  src/main/java/com/debatetimer/config/NotifierConfig.java
  src/main/java/com/debatetimer/exception/errorcode/InitializationErrorCode.java
  src/main/java/com/debatetimer/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/debatetimer/service/auth/AuthService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/test/java/com/debatetimer/DatabaseSchemaManagerTest.java
  src/test/java/com/debatetimer/DebateTimerApplicationTest.java
  src/test/java/com/debatetimer/client/DiscordPropertiesTest.java
  src/test/java/com/debatetimer/client/OAuthPropertiesTest.java
  src/test/java/com/debatetimer/controller/BaseControllerTest.java
Labels: feat

#132 [HOTFIX] NullException처리
  src/main/java/com/debatetimer/dto/customize/response/CustomizeTimeBoxResponse.java
  src/main/java/com/debatetimer/dto/parliamentary/response/ParliamentaryTableResponse.java
  src/main/java/com/debatetimer/dto/parliamentary/response/ParliamentaryTimeBoxResponse.java
  src/main/java/com/debatetimer/dto/timebased/response/TimeBasedTableResponse.java
  src/main/java/com/debatetimer/dto/timebased/response/TimeBasedTimeBoxResponse.java
  src/test/java/com/debatetimer/controller/customize/CustomizeControllerTest.java
  src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerTest.java
  src/test/java/com/debatetimer/controller/timebased/TimeBasedControllerTest.java
  src/test/java/com/debatetimer/fixture/CustomizeTimeBoxGenerator.java
  src/test/java/com/debatetimer/fixture/ParliamentaryTimeBoxGenerator.java
  src/test/java/com/debatetimer/fixture/TimeBasedTimeBoxGenerator.java
Labels: hotfix
