Repository debate-timer/debate-timer-be, pull requests merged in 2025-07, with the labels that each got.

#189 chore : 코드레빗 설정파일 추가
  .coderabbit.yaml
Labels: chore

#196 [FEAT] 투표 API 기초 엔티티 세팅
  src/main/java/com/debatetimer/domain/poll/PollStatus.java
  src/main/java/com/debatetimer/domain/poll/VoteTeam.java
  src/main/java/com/debatetimer/entity/poll/PollEntity.java
  src/main/java/com/debatetimer/entity/poll/VoteEntity.java
  src/main/resources/db/migration/V9__create_poll_and_vote_table.sql
Labels: feat

#197 [CHORE] 커스텀 메트릭 지표 논의 및 구현
  src/main/java/com/debatetimer/client/notifier/DiscordNotifier.java
  src/main/java/com/debatetimer/client/oauth/OAuthClient.java
  src/main/java/com/debatetimer/config/MonitoringConfig.java
Labels: chore

#201 [REFACTOR] 타임박스 도메인 - 엔티티 분리 / 서비스 로직 개선
  src/main/java/com/debatetimer/domain/customize/CustomizeTimeBoxEntities.java
  src/main/java/com/debatetimer/dto/customize/request/CustomizeTableCreateRequest.java
  src/main/java/com/debatetimer/dto/customize/response/CustomizeTableResponse.java
  src/main/java/com/debatetimer/dto/customize/response/CustomizeTimeBoxResponse.java
  src/main/java/com/debatetimer/entity/customize/BellEntity.java
  src/main/java/com/debatetimer/entity/customize/CustomizeTimeBoxEntities.java
  src/main/java/com/debatetimer/entity/customize/CustomizeTimeBoxEntity.java
  src/main/java/com/debatetimer/repository/customize/BellRepository.java
  src/main/java/com/debatetimer/repository/customize/CustomizeTimeBoxRepository.java
  src/main/java/com/debatetimer/service/customize/CustomizeService.java
  src/main/java/com/debatetimer/service/customize/CustomizeServiceV2.java
  src/test/java/com/debatetimer/entity/customize/CustomizeTimeBoxEntitiesTest.java
  src/test/java/com/debatetimer/repository/BaseRepositoryTest.java
  src/test/java/com/debatetimer/repository/customize/BellRepositoryTest.java
  src/test/java/com/debatetimer/repository/customize/CustomizeTimeBoxRepositoryTest.java
  src/test/java/com/debatetimer/service/customize/CustomizeServiceV2Test.java
Labels: refactor

#203 [FEAT] 투표 개최자 API 구현
  src/main/java/com/debatetimer/controller/poll/PollController.java
  src/main/java/com/debatetimer/domain/poll/ParticipantName.java
  src/main/java/com/debatetimer/domain/poll/ParticipateCode.java
  src/main/java/com/debatetimer/domain/poll/Poll.java
  src/main/java/com/debatetimer/domain/poll/Vote.java
  src/main/java/com/debatetimer/domain/poll/VoteInfo.java
  src/main/java/com/debatetimer/domainrepository/poll/CustomizeTableDomainRepository.java
  src/main/java/com/debatetimer/domainrepository/poll/PollDomainRepository.java
  src/main/java/com/debatetimer/domainrepository/poll/VoteDomainRepository.java
  src/main/java/com/debatetimer/dto/poll/response/PollCreateResponse.java
  src/main/java/com/debatetimer/dto/poll/response/PollInfoResponse.java
  src/main/java/com/debatetimer/entity/poll/PollEntity.java
  src/main/java/com/debatetimer/entity/poll/VoteEntity.java
  src/main/java/com/debatetimer/exception/errorcode/ClientErrorCode.java
  src/main/java/com/debatetimer/repository/poll/PollRepository.java
  src/main/java/com/debatetimer/repository/poll/VoteRepository.java
  src/main/java/com/debatetimer/service/poll/PollService.java
  src/main/resources/db/migration/V11__add_memberId_into_poll.sql
  src/test/java/com/debatetimer/controller/BaseControllerTest.java
  src/test/java/com/debatetimer/controller/BaseDocumentTest.java
  src/test/java/com/debatetimer/controller/Tag.java
  src/test/java/com/debatetimer/controller/poll/PollControllerTest.java
  src/test/java/com/debatetimer/controller/poll/PollDocumentTest.java
  src/test/java/com/debatetimer/domain/poll/ParticipantNameTest.java
  src/test/java/com/debatetimer/domain/poll/ParticipateCodeTest.java
  src/test/java/com/debatetimer/domainrepository/BaseDomainRepositoryTest.java
  src/test/java/com/debatetimer/domainrepository/poll/PollDomainRepositoryTest.java
  src/test/java/com/debatetimer/domainrepository/poll/VoteDomainRepositoryTest.java
  src/test/java/com/debatetimer/fixture/PollGenerator.java
  src/test/java/com/debatetimer/fixture/VoteGenerator.java
  src/test/java/com/debatetimer/repository/BaseRepositoryTest.java
  src/test/java/com/debatetimer/service/BaseServiceTest.java
  src/test/java/com/debatetimer/service/poll/PollServiceTest.java
Labels: feat

#211 [CHORE] 정상 배포 확인을 위한 헬스 체크 기능 구현
  .github/workflows/Dev_CD.yml
  .github/workflows/Prod_CD.yml
  scripts/dev/health-check.sh
  scripts/prod/health-check.sh
Labels: chore
