Repository debate-timer/debate-timer-be, pull requests merged in 2025-01, with the labels that each got.

#38 [FEAT] TimeBox CRUD 구현
  src/main/java/com/debatetimer/config/AuthMemberArgumentResolver.java
  src/main/java/com/debatetimer/config/WebConfig.java
  src/main/java/com/debatetimer/controller/auth/AuthMember.java
  src/main/java/com/debatetimer/controller/member/MemberController.java
  src/main/java/com/debatetimer/controller/member/MemberControllerSwagger.java
  src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryController.java
  src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerSwagger.java
  src/main/java/com/debatetimer/domain/BoxType.java
  src/main/java/com/debatetimer/domain/member/Member.java
  src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTable.java
  src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBox.java
  src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBoxes.java
  src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableCreateRequest.java
  src/main/java/com/debatetimer/dto/parliamentary/request/TableInfoCreateRequest.java
  src/main/java/com/debatetimer/dto/parliamentary/request/TimeBoxCreateRequest.java
  src/main/java/com/debatetimer/dto/parliamentary/response/ParliamentaryTableResponse.java
  src/main/java/com/debatetimer/dto/parliamentary/response/TableInfoResponse.java
  src/main/java/com/debatetimer/dto/parliamentary/response/TimeBoxResponse.java
  src/main/java/com/debatetimer/exception/ErrorResponse.java
  src/main/java/com/debatetimer/exception/custom/DTClientErrorException.java
  src/main/java/com/debatetimer/exception/custom/DTException.java
  src/main/java/com/debatetimer/exception/custom/DTServerErrorException.java
  src/main/java/com/debatetimer/exception/errorcode/ClientErrorCode.java
  src/main/java/com/debatetimer/exception/errorcode/ErrorCode.java
  src/main/java/com/debatetimer/exception/errorcode/ServerErrorCode.java
  src/main/java/com/debatetimer/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/debatetimer/repository/member/MemberRepository.java
  src/main/java/com/debatetimer/repository/parliamentary/ParliamentaryTableRepository.java
  src/main/java/com/debatetimer/repository/parliamentary/ParliamentaryTimeBoxRepository.java
  src/main/java/com/debatetimer/service/member/MemberService.java
  src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
  src/main/java/com/debatetimer/swagger/annotation/ErrorCode400.java
  src/main/java/com/debatetimer/swagger/annotation/ErrorCode401.java
  src/main/java/com/debatetimer/swagger/annotation/ErrorCode404.java
  src/main/java/com/debatetimer/swagger/annotation/ErrorCode500.java
  src/main/resources/application.yml
  src/test/java/com/debatetimer/BaseControllerTest.java
  src/test/java/com/debatetimer/BaseRepositoryTest.java
  src/test/java/com/debatetimer/BaseServiceTest.java
  src/test/java/com/debatetimer/DataBaseCleaner.java
  src/test/java/com/debatetimer/DebateTimerApplicationTest.java
  src/test/java/com/debatetimer/controller/member/MemberControllerTest.java
  src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerTest.java
  src/test/java/com/debatetimer/domain/member/MemberTest.java
  src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBoxTest.java
  src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBoxesTest.java
  src/test/java/com/debatetimer/fixture/DtoGenerator.java
  src/test/java/com/debatetimer/fixture/FixtureGenerator.java
  src/test/java/com/debatetimer/repository/parliamentary/ParliamentaryTableRepositoryTest.java
  src/test/java/com/debatetimer/repository/parliamentary/ParliamentaryTimeBoxRepositoryTest.java
  src/test/java/com/debatetimer/service/member/MemberServiceTest.java
  src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
Labels: feat

#42 [REFACTOR] 자바 표준 예외를 커스텀 예외로 통일
  src/main/java/com/debatetimer/config/AuthMemberArgumentResolver.java
  src/main/java/com/debatetimer/domain/member/Member.java
  src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTable.java
  src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBox.java
  src/main/java/com/debatetimer/exception/custom/DTException.java
  src/main/java/com/debatetimer/exception/errorcode/ClientErrorCode.java
  src/main/java/com/debatetimer/repository/member/MemberRepository.java
  src/main/java/com/debatetimer/service/member/MemberService.java
  src/test/java/com/debatetimer/domain/member/MemberTest.java
  src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTableTest.java
  src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBoxTest.java
  src/test/java/com/debatetimer/repository/parliamentary/ParliamentaryTableRepositoryTest.java
Labels: refactor

#43 [TEST] generator 컨벤션에 맞추어 코드 수정
  src/main/java/com/debatetimer/dto/parliamentary/request/TimeBoxCreateRequest.java
  src/main/java/com/debatetimer/service/member/MemberService.java
  src/test/java/com/debatetimer/BaseControllerTest.java
  src/test/java/com/debatetimer/BaseRepositoryTest.java
  src/test/java/com/debatetimer/BaseServiceTest.java
  src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerTest.java
  src/test/java/com/debatetimer/fixture/DtoGenerator.java
  src/test/java/com/debatetimer/fixture/FixtureGenerator.java
  src/test/java/com/debatetimer/fixture/MemberGenerator.java
  src/test/java/com/debatetimer/fixture/ParliamentaryTableGenerator.java
  src/test/java/com/debatetimer/fixture/ParliamentaryTimeBoxGenerator.java
  src/test/java/com/debatetimer/repository/parliamentary/ParliamentaryTableRepositoryTest.java
  src/test/java/com/debatetimer/repository/parliamentary/ParliamentaryTimeBoxRepositoryTest.java
  src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
Labels: test

#44 [CHORE] Swagger + Rest Docs 로 API 문서 생성
  .gitignore
  build.gradle
  src/main/java/com/debatetimer/controller/auth/AuthMember.java
  src/main/java/com/debatetimer/controller/member/MemberController.java
  src/main/java/com/debatetimer/controller/member/MemberControllerSwagger.java
  src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryController.java
  src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerSwagger.java
  src/main/java/com/debatetimer/domain/member/Member.java
  src/main/java/com/debatetimer/dto/member/MemberCreateRequest.java
  src/main/java/com/debatetimer/dto/member/MemberCreateResponse.java
  src/main/java/com/debatetimer/dto/member/TableResponse.java
  src/main/java/com/debatetimer/dto/member/TableResponses.java
  src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableCreateRequest.java
  src/main/java/com/debatetimer/dto/parliamentary/request/TableInfoCreateRequest.java
  src/main/java/com/debatetimer/dto/parliamentary/request/TimeBoxCreateRequest.java
  src/main/java/com/debatetimer/dto/parliamentary/response/ParliamentaryTableResponse.java
  src/main/java/com/debatetimer/dto/parliamentary/response/TableInfoResponse.java
  src/main/java/com/debatetimer/dto/parliamentary/response/TimeBoxResponse.java
  src/main/java/com/debatetimer/exception/ErrorResponse.java
  src/main/java/com/debatetimer/swagger/annotation/ErrorCode400.java
  src/main/java/com/debatetimer/swagger/annotation/ErrorCode401.java
  src/main/java/com/debatetimer/swagger/annotation/ErrorCode404.java
  src/main/java/com/debatetimer/swagger/annotation/ErrorCode500.java
  src/main/java/com/debatetimer/swagger/config/SwaggerConfig.java
  src/main/resources/application.yml
  src/main/resources/static/docs/.gitkeep
  src/test/java/com/debatetimer/controller/BaseControllerTest.java
  src/test/java/com/debatetimer/controller/BaseDocumentTest.java
  src/test/java/com/debatetimer/controller/RestDocumentationFilterBuilder.java
  src/test/java/com/debatetimer/controller/RestDocumentationRequest.java
  src/test/java/com/debatetimer/controller/RestDocumentationResponse.java
  src/test/java/com/debatetimer/controller/Tag.java
  src/test/java/com/debatetimer/controller/member/MemberControllerTest.java
  src/test/java/com/debatetimer/controller/member/MemberDocumentTest.java
  src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerTest.java
  src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryDocumentTest.java
Labels: chore

#54 [TEST] BaseTest 파일 패키지 옮기기
  src/test/java/com/debatetimer/repository/BaseRepositoryTest.java
  src/test/java/com/debatetimer/repository/parliamentary/ParliamentaryTableRepositoryTest.java
  src/test/java/com/debatetimer/repository/parliamentary/ParliamentaryTimeBoxRepositoryTest.java
  src/test/java/com/debatetimer/service/BaseServiceTest.java
  src/test/java/com/debatetimer/service/member/MemberServiceTest.java
  src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
Labels: test

#52 [FIX] 멤버 테이블 조회 요청 수정
  src/main/java/com/debatetimer/dto/member/TableResponse.java
  src/test/java/com/debatetimer/controller/member/MemberDocumentTest.java
Labels: fix

#56 [CHORE] Discord 알림 embeds 개선
  .github/workflows/PR_Comment_Notification.yml
Labels: chore

#53 [REFACTOR] Repository 상속 객체 전환
  src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBoxes.java
  src/main/java/com/debatetimer/repository/member/MemberRepository.java
  src/main/java/com/debatetimer/repository/parliamentary/ParliamentaryTableRepository.java
  src/main/java/com/debatetimer/repository/parliamentary/ParliamentaryTimeBoxRepository.java
  src/main/java/com/debatetimer/service/member/MemberService.java
  src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
  src/test/java/com/debatetimer/service/member/MemberServiceTest.java
  src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
Labels: refactor

#49 [FEAT] Excel export 추가 기능 구현
  build.gradle
  src/main/java/com/debatetimer/exception/errorcode/ServerErrorCode.java
  src/main/java/com/debatetimer/view/exporter/BoxTypeView.java
  src/main/java/com/debatetimer/view/exporter/ParliamentaryTableExcelExporter.java
  src/main/java/com/debatetimer/view/exporter/ParliamentaryTableExportMessageResolver.java
  src/test/java/com/debatetimer/view/exporter/BoxTypeViewTest.java
Labels: feat

#63 [CHORE] PR 리뷰 작성 시, 알림이 안가는 문제 해결
  .github/workflows/PR_Comment_Notification.yml
Labels: chore

#60 [CHORE] prod 환경 분리
  .github/workflows/Prod_CD.yml
  .github/workflows/Prod_CI.yml
  scripts/prod/replace-new-version.sh
  src/main/resources/application-prod.yml
  src/main/resources/prod-secret.yml
Labels: chore

#58 [CHORE] DEV_CD 파이프라인 구축 + application-dev.yml 작성
  .github/workflows/Dev_CD.yml
  build.gradle
  scripts/dev/replace-new-version.sh
  src/main/resources/application-dev.yml
  src/main/resources/dev-secret.yml
Labels: chore

#66 [CHORE] PR 리뷰 작성 시, 알림이 안가는 문제 해결
  .github/workflows/PR_Comment_Notification.yml
Labels: chore

#67 [REFACTOR] 테이블 명에 숫자를 허용하도록 수정
  src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTable.java
  src/main/java/com/debatetimer/exception/errorcode/ClientErrorCode.java
  src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTableTest.java
Labels: refactor

#70 [FIX] 임시 로그인 API 수정
  src/main/java/com/debatetimer/repository/member/MemberRepository.java
  src/main/java/com/debatetimer/service/member/MemberService.java
  src/test/java/com/debatetimer/service/member/MemberServiceTest.java
Labels: fix

#75 [FEAT] CORS 설정
  src/main/java/com/debatetimer/config/CorsConfig.java
Labels: feat

#82 [FEAT] 반환값에 종소리 flag값 추가
  src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTable.java
  src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableCreateRequest.java
  src/main/java/com/debatetimer/dto/parliamentary/request/TableInfoCreateRequest.java
  src/main/java/com/debatetimer/dto/parliamentary/response/TableInfoResponse.java
  src/main/resources/application-local.yml
  src/test/java/com/debatetimer/controller/member/MemberControllerTest.java
  src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerTest.java
  src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryDocumentTest.java
  src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTableTest.java
  src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBoxesTest.java
  src/test/java/com/debatetimer/fixture/ParliamentaryTableGenerator.java
  src/test/java/com/debatetimer/service/member/MemberServiceTest.java
  src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
Labels: feat
