Repository debate-timer/debate-timer-be, pull requests merged in 2025-05, with the labels that each got.

#156 [REFACTOR] 시간 총량제 삭제
  src/main/java/com/debatetimer/controller/timebased/TimeBasedController.java
  src/main/java/com/debatetimer/controller/tool/export/ExcelExportInterceptor.java
  src/main/java/com/debatetimer/domain/timebased/TimeBasedBoxType.java
  src/main/java/com/debatetimer/domain/timebased/TimeBasedTable.java
  src/main/java/com/debatetimer/domain/timebased/TimeBasedTimeBox.java
  src/main/java/com/debatetimer/dto/timebased/request/TimeBasedTableCreateRequest.java
  src/main/java/com/debatetimer/dto/timebased/request/TimeBasedTableInfoCreateRequest.java
  src/main/java/com/debatetimer/dto/timebased/request/TimeBasedTimeBoxCreateRequest.java
  src/main/java/com/debatetimer/dto/timebased/response/TimeBasedTableInfoResponse.java
  src/main/java/com/debatetimer/dto/timebased/response/TimeBasedTableResponse.java
  src/main/java/com/debatetimer/dto/timebased/response/TimeBasedTimeBoxResponse.java
  src/main/java/com/debatetimer/exception/errorcode/ClientErrorCode.java
  src/main/java/com/debatetimer/repository/timebased/TimeBasedTableRepository.java
  src/main/java/com/debatetimer/repository/timebased/TimeBasedTimeBoxRepository.java
  src/main/java/com/debatetimer/service/timebased/TimeBasedService.java
  src/test/java/com/debatetimer/controller/BaseControllerTest.java
  src/test/java/com/debatetimer/controller/BaseDocumentTest.java
  src/test/java/com/debatetimer/controller/timebased/TimeBasedControllerTest.java
  src/test/java/com/debatetimer/controller/timebased/TimeBasedDocumentTest.java
  src/test/java/com/debatetimer/domain/timebased/TimeBasedTableTest.java
  src/test/java/com/debatetimer/domain/timebased/TimeBasedTimeBoxTest.java
  src/test/java/com/debatetimer/fixture/HeaderGenerator.java
  src/test/java/com/debatetimer/fixture/TimeBasedTableGenerator.java
  src/test/java/com/debatetimer/fixture/TimeBasedTimeBoxGenerator.java
  src/test/java/com/debatetimer/repository/BaseRepositoryTest.java
  src/test/java/com/debatetimer/repository/timebased/TimeBasedTableRepositoryTest.java
  src/test/java/com/debatetimer/repository/timebased/TimeBasedTimeBoxRepositoryTest.java
  src/test/java/com/debatetimer/service/BaseServiceTest.java
  src/test/java/com/debatetimer/service/timebased/TimeBasedServiceTest.java
Labels: refactor

#158 [CHORE] Datadog APM 설정
  scripts/dev/replace-new-version.sh
  scripts/prod/replace-new-version.sh
Labels: chore

#164 [CHORE] DataDog을 통한 로그 수집
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/logging/log4j2-dev.yml
  src/main/resources/logging/log4j2-prod.yml
Labels: chore

#166 [DOCS] Swagger를 통해 추가 설명 제시
  src/main/resources/application.yml
  src/test/java/com/debatetimer/controller/RestDocumentationRequest.java
  src/test/java/com/debatetimer/controller/customize/CustomizeDocumentTest.java
  src/test/java/com/debatetimer/controller/member/MemberDocumentTest.java
Labels: docs

#168 [FIX] '토론 테이블 변경 API' 동시성 문제
  src/main/java/com/debatetimer/service/customize/CustomizeService.java
  src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
  src/test/java/com/debatetimer/service/BaseServiceTest.java
  src/test/java/com/debatetimer/service/customize/CustomizeServiceTest.java
  src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
Labels: fix

#172 [CHORE] 의회식 토론 api 제거
  src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryController.java
  src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryBoxType.java
  src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTable.java
  src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBox.java
  src/main/java/com/debatetimer/dto/member/TableResponses.java
  src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableCreateRequest.java
  src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableInfoCreateRequest.java
  src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTimeBoxCreateRequest.java
  src/main/java/com/debatetimer/dto/parliamentary/response/ParliamentaryTableInfoResponse.java
  src/main/java/com/debatetimer/dto/parliamentary/response/ParliamentaryTableResponse.java
  src/main/java/com/debatetimer/dto/parliamentary/response/ParliamentaryTimeBoxResponse.java
  src/main/java/com/debatetimer/repository/parliamentary/ParliamentaryTableRepository.java
  src/main/java/com/debatetimer/repository/parliamentary/ParliamentaryTimeBoxRepository.java
  src/main/java/com/debatetimer/service/member/MemberService.java
  src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
  src/main/java/com/debatetimer/view/exporter/ParliamentaryBoxTypeView.java
  src/main/java/com/debatetimer/view/exporter/ParliamentaryTableExcelExporter.java
  src/main/java/com/debatetimer/view/exporter/ParliamentaryTableExportMessageResolver.java
  src/main/resources/db/migration/V8__drop_parliamnetary_table_and_box.sql
  src/test/java/com/debatetimer/controller/BaseControllerTest.java
  src/test/java/com/debatetimer/controller/BaseDocumentTest.java
  src/test/java/com/debatetimer/controller/member/MemberControllerTest.java
  src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerTest.java
  src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryDocumentTest.java
  src/test/java/com/debatetimer/domain/TimeBoxesTest.java
  src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTableTest.java
  src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBoxTest.java
  src/test/java/com/debatetimer/fixture/ParliamentaryTableGenerator.java
  src/test/java/com/debatetimer/fixture/ParliamentaryTimeBoxGenerator.java
  src/test/java/com/debatetimer/repository/BaseRepositoryTest.java
  src/test/java/com/debatetimer/repository/parliamentary/ParliamentaryTableRepositoryTest.java
  src/test/java/com/debatetimer/repository/parliamentary/ParliamentaryTimeBoxRepositoryTest.java
  src/test/java/com/debatetimer/service/BaseServiceTest.java
  src/test/java/com/debatetimer/service/member/MemberServiceTest.java
  src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
  src/test/java/com/debatetimer/view/exporter/ParliamentaryBoxTypeViewTest.java
Labels: chore

#174 [TEST] DTO Null, Blank E2E Test
  build.gradle
  src/main/java/com/debatetimer/aop/logging/ClientLoggingAspect.java
  src/main/java/com/debatetimer/aop/logging/LoggingClient.java
  src/main/java/com/debatetimer/client/notifier/DiscordNotifier.java
  src/main/java/com/debatetimer/config/NotifierConfig.java
  src/main/java/com/debatetimer/controller/auth/AuthMember.java
  src/main/java/com/debatetimer/controller/member/MemberController.java
  src/test/java/com/debatetimer/controller/BaseControllerTest.java
  src/test/java/com/debatetimer/controller/customize/CustomizeControllerTest.java
  src/test/java/com/debatetimer/controller/member/MemberControllerTest.java
  src/test/java/com/debatetimer/domain/DebateTableTest.java
  src/test/java/com/debatetimer/fixture/BlankArgumentsProvider.java
  src/test/java/com/debatetimer/fixture/NullAndEmptyAndBlankSource.java
  src/test/java/com/debatetimer/repository/customize/CustomizeTableRepositoryTest.java
  src/test/java/com/debatetimer/repository/customize/CustomizeTimeBoxRepositoryTest.java
Labels: test

#173 [FIX] '토론 테이블 변경 API' 동시성 문제
  src/main/java/com/debatetimer/repository/customize/CustomizeTableRepository.java
  src/main/java/com/debatetimer/service/customize/CustomizeService.java
  src/test/java/com/debatetimer/controller/customize/CustomizeDocumentTest.java
  src/test/java/com/debatetimer/repository/customize/CustomizeTableRepositoryTest.java
  src/test/java/com/debatetimer/service/customize/CustomizeServiceTest.java
Labels: fix

#177 [REFACTOR] MappedSuperClass 제거
  src/main/java/com/debatetimer/domain/DebateTable.java
  src/main/java/com/debatetimer/domain/DebateTimeBox.java
  src/main/java/com/debatetimer/domain/TimeBoxes.java
  src/main/java/com/debatetimer/domain/customize/CustomizeTable.java
  src/main/java/com/debatetimer/domain/customize/CustomizeTimeBox.java
  src/main/java/com/debatetimer/domain/customize/CustomizeTimeBoxes.java
  src/main/java/com/debatetimer/dto/customize/request/CustomizeTableCreateRequest.java
  src/main/java/com/debatetimer/dto/customize/response/CustomizeTableResponse.java
  src/main/java/com/debatetimer/dto/member/TableResponse.java
  src/main/java/com/debatetimer/dto/member/TableResponses.java
  src/main/java/com/debatetimer/dto/member/TableType.java
  src/main/java/com/debatetimer/exception/errorcode/ClientErrorCode.java
  src/main/java/com/debatetimer/repository/customize/CustomizeTimeBoxRepository.java
  src/main/java/com/debatetimer/service/customize/CustomizeService.java
  src/test/java/com/debatetimer/controller/member/MemberDocumentTest.java
  src/test/java/com/debatetimer/domain/DebateTableTest.java
  src/test/java/com/debatetimer/domain/DebateTimeBoxTest.java
  src/test/java/com/debatetimer/domain/customize/CustomizeTableTest.java
  src/test/java/com/debatetimer/domain/customize/CustomizeTimeBoxTest.java
  src/test/java/com/debatetimer/domain/customize/CustomizeTimeBoxesTest.java
Labels: refactor

#178 [CHORE] DataDog을 통한 로그 수집
  src/main/resources/logging/log4j2-dev.yml
  src/main/resources/logging/log4j2-prod.yml
Labels: chore

#179 [CHORE] DataDog을 통한 로그 수집
  src/main/resources/logging/log4j2-dev.yml
  src/main/resources/logging/log4j2-prod.yml
Labels: chore

#180 [FEAT] MultipartException 처리
  src/main/java/com/debatetimer/exception/errorcode/ClientErrorCode.java
  src/main/java/com/debatetimer/exception/handler/GlobalExceptionHandler.java
Labels: feat

#184 [REFACTOR] 타임 박스 삭제&저장 동시성 이슈 리팩토링
  src/main/java/com/debatetimer/repository/customize/CustomizeTableRepository.java
  src/main/java/com/debatetimer/repository/customize/CustomizeTimeBoxRepository.java
  src/main/java/com/debatetimer/service/customize/CustomizeService.java
  src/test/java/com/debatetimer/repository/customize/CustomizeTableRepositoryTest.java
  src/test/java/com/debatetimer/repository/customize/CustomizeTimeBoxRepositoryTest.java
Labels: refactor
